version: "3.8"
services:
  test-game:
    image: keihatsu/test-game:latest
    build: .
    container_name: something_funny
    ports:
      - "80:3000"
    environment:
      - PORT=3000
    volumes:
      - ./:/app
    command: ["node", "app.js"]